Description: AWS CloudFormation Template to create an S3 Bucket for Udagram Project

Parameters:
  EnvBucketName:
    Description: The name of the S3 bucket for the environment
    Type: String

Resources:
  WebS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvBucketName}-s3-mg-20260112"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Status: "Enabled"
            NoncurrentVersionExpirationInDays: 10
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs:
  WebS3BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref WebS3Bucket
  WebS3BucketArn:
    Description: "ARN of the S3 bucket"
    Value: !GetAtt WebS3Bucket.Arn
    Export:
      Name: !Sub "${EnvBucketName}-S3BucketARN"